/*
 * File: pa4Strings.h
 * Description: Header file containing strings that are displayed to the user.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA1_STRINGS_H    /* Macro guard */
#define PA1_STRINGS_H


/* Usage string */
#define STR_USAGE "\nUsage: %s height border_char filler_char windmill_char\n"\
  "   height        (must be odd within the range of [%d - %d])\n"\
  "   border_char   (must be single char within the ASCII range [%d - %d])\n"\
  "                 (must be different than windmill_char)\n"\
  "   filler_char   (must be single char within the ASCII range [%d - %d])\n"\
  "   windmill_char (must be single char within the ASCII range [%d - %d])\n"\
  "                 (must be different than border_char)\n\n"


/* You will need to use these within some of the error messages */
#define STR_HEIGHT "height"
#define STR_BORDER_CHAR "border_char"
#define STR_FILLER_CHAR "filler_char"
#define STR_WINDMILL_CHAR "windmill_char"


/* Error strings */
#define STR_ERR_NUM_RANGE "\n\t %s(%ld) must be within the range of [%d - %d]\n"

#define STR_ERR_ODD "\n\t %s(%ld) must be an odd number\n"

#define STR_ERR_CONVERTING "\n\t converting %s(%s) in base(%d) to long"

#define STR_ERR_SINGLE_CHAR "\n\t %s(%s) must be a single character\n"

#define STR_ERR_NOT_INT "\n\t %s(%s) must be an integer\n"

#define STR_ERR_ASCII_RANGE "\n\t %s(%c) must be within the ASCII range"\
  " [%d - %d]\n"

#define STR_ERR_BORDER_WINDMILL_DIFF "\n\t border_char(%c) and"\
  " windmill_char(%c) must be different\n"

#define STR_ERR_FILLER_WINDMILL_DIFF "\n\t filler_char(%c) and"\
  " windmill_char(%c) must be different\n"


#endif /* PA1_STRINGS_H */
